---
title: "Capstone_Divisions"
author: "Lael Hebert"
date: "April 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
# library(tidyr)
# stops_summary_all_years_with_pop <- read_csv("~/Learning/Springboard/Introduction to Data Science/Capstone/Data/Output/stops_summary_all_years_with_pop.csv")
stops_summary_by_year_with_pop <- read_csv("~/Learning/Springboard/Introduction to Data Science/Capstone/Data/Output/stops_summary_by_year_with_pop.csv", 
     col_types = cols(ethnicity_count = col_double()))
# stop_type_by_ethnicity_citywide_all_years <- read_csv("~/Learning/Springboard/Introduction to Data Science/Capstone/Data/Output/stop_type_by_ethnicity_citywide_all_years.csv")
```

Graph vehicular vs pedestrians stops

```{r echo=FALSE}

```
Graph division trends

```{r echo=FALSE}

division_black_trend_graph <- function(div) {
  stops_summary_by_year_with_pop %>% 
  filter(division == div, ethnicity == "BLACK", location == "stops", year != 2019) %>%
  ggplot(aes(x = year, y = ethnicity_percent)) + geom_point() + 
  geom_smooth(method = 'lm', formula = y~x) +
  ggtitle(paste(div,"Black Stops"))
}

division_black_lm_summary <- function(div) {
 summary(lm(ethnicity_percent ~ year, filter(stops_summary_by_year_with_pop, division == div, ethnicity == "BLACK", location == "stops"))) 
}


#In scope:
division_black_trend_graph("SOUTHEAST")
division_black_lm_summary("SOUTHEAST")

division_black_trend_graph("SOUTHWEST")
division_black_lm_summary("SOUTHWEST")

division_black_trend_graph("CENTRAL")
division_black_lm_summary("CENTRAL")

division_black_trend_graph("NEWTON")
division_black_lm_summary("NEWTON")

division_black_trend_graph("HOLLYWOOD")
division_black_lm_summary("HOLLYWOOD")

division_black_trend_graph("OLYMPIC")
division_black_lm_summary("OLYMPIC")

#Out of scope:
division_black_trend_graph("77TH STREET")
division_black_lm_summary("77TH STREET")

division_black_trend_graph("WILSHIRE")
division_black_lm_summary("WILSHIRE")

division_black_trend_graph("PACIFIC")
division_black_lm_summary("PACIFIC")

division_black_trend_graph("HARBOR")
division_black_lm_summary("HARBOR")

division_black_trend_graph("DEVONSHIRE")
division_black_lm_summary("DEVONSHIRE")

division_black_trend_graph("NORTH HOLLYWOOD")
division_black_lm_summary("NORTH HOLLYWOOD")

division_black_trend_graph("TOPANGA")
division_black_lm_summary("TOPANGA")

division_black_trend_graph("VAN NUYS")
division_black_lm_summary("VAN NUYS")

division_black_trend_graph("RAMPART")
division_black_lm_summary("RAMPART")

division_black_trend_graph("WEST LOS ANGELES")
division_black_lm_summary("WEST LOS ANGELES")

division_black_trend_graph("WEST VALLEY")
division_black_lm_summary("WEST VALLEY")

division_black_trend_graph("FOOTHILL")
division_black_lm_summary("FOOTHILL")

division_black_trend_graph("NORTHEAST")
division_black_lm_summary("NORTHEAST")

division_black_trend_graph("MISSION")
division_black_lm_summary("MISSION")

division_black_trend_graph("HOLLENBECK")
division_black_lm_summary("HOLLENBECK")

division_black_trend_graph("CITY TOTAL")
division_black_lm_summary("CITY TOTAL")

```


Yearly graphs of black percentages of stops to population
```{r echo=FALSE}
graph_black_percentages_divisions_year <- function(yr) {
  stops_summary_by_year_with_pop %>%
  filter(division != "CITY TOTAL", year == yr | location == "population", ethnicity == "BLACK") %>%
  select(1,3,5,6) %>%
  spread(key = location, value = ethnicity_percent) %>%
  ggplot(aes(x=population, y=stops, col = division)) + 
    geom_point() + ylim(0,.7) +
  ggtitle(paste("Black percentages by divsion ", yr))
}

graph_black_percentages_divisions_year(2010)
graph_black_percentages_divisions_year(2011)
graph_black_percentages_divisions_year(2012)
graph_black_percentages_divisions_year(2013)
graph_black_percentages_divisions_year(2014)
graph_black_percentages_divisions_year(2015)
graph_black_percentages_divisions_year(2016)
graph_black_percentages_divisions_year(2017)
graph_black_percentages_divisions_year(2018)

```


Graph vehicular vs pedestrians stops

```{r echo=FALSE}
officer_black_stops_by_division_and_year <- read_csv("~/Learning/Springboard/Introduction to Data Science/Capstone/Data/Output/officer_black_stops_by_division_and_year.csv")

#officer_black_stops_by_division_and_year %>%
#  filter(year == 2018, division == "HOLLYWOOD") %>%
#  ggplot(aes(total_stops)) + geom_histogram(binwidth = 100)

off_div_black_perc_hist <- function(y, div, bw) {
  officer_black_stops_by_division_and_year %>%
    filter(year == y, division == div, total_stops >= 100) %>%
    ggplot(aes(officer_black_stop_percent)) + geom_histogram(binwidth = bw)
}

off_div_black_perc_hist(2018, "HOLLYWOOD", 0.05)



```



